name: "Run tests"
description: "Runs the tests and downloads a build artifact"

runs:
  using: "composite"
  steps:
    - name: Install Rust
      shell: bash -euxo pipefail
      run: |
        cargo install cargo-nextest

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Limit target directory size
      shell: bash -euxo pipefail
      run: script/clear-target-dir-if-larger-than 100

    - name: Run tests
      shell: bash -euxo pipefail
      run: cargo nextest run --workspace --no-fail-fast

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: build-artifact # Specify the name of the artifact if you have a specific name
        # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
        path: ./artifacts # Specify the destination path where the artifact will be downloaded
        # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
        # pattern: # Optional
        # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
        merge-multiple: true # Set to true if you want to merge multiple artifacts into the same directory
        # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
        # github-token: ${{ secrets.GITHUB_TOKEN }} # Optional, only required for different repositories
        # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
        # repository: # Optional, only required for different repositories
        # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
        # run-id: # Optional, default is ${{ github.run_id }}
