name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build
        run: cargo build --release --verbose --target x86_64-pc-windows-msvc

      - name: Run Application
        run: cargo run --release --verbose --target x86_64-pc-windows-msvc

      - name: Create Windows Bundle
        run: cargo bundle --release --target x86_64-pc-windows-msvc

      - name: Upload app bundle to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-pc-windows-msvc/release/your_project_name.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
