name: Build Zed Nightly

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:     # (optional) lets you run it manually from the GitHub UI

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        backend: [vulkan, opengl]
        include:
          - backend: vulkan
            artifact_name: zed-release
            rustflags: ""
          - backend: opengl
            artifact_name: zed-release-opengl
            rustflags: "--cfg gles"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.backend }}

      - name: Build release
        run: cargo build --release
        env:
          RUSTFLAGS: "-C target-feature=-crt-static ${{ matrix.rustflags }}"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/zed.exe
